#pragma once

typedef enum {SNOWY_PLAINS, ICE_SPIKES, SNOWY_TUNDRA, SNOWY_TAIGA, TAIGA,
PLAINS, FOREST, OLD_GROWTH_SPRUCE_TAIGA, OLD_GROWTH_PINE_TAIGA, FLOWER_FOREST,
SUNFLOWER_PLAINS, BIRCH_FOREST, OLD_GROWTH_BIRCH_FOREST, DARK_FOREST,
SAVANNA, JUNGLE, SPARSE_JUNGLE, BAMBOO_JUNGLE, DESERT, SNOWY_SLOPES,
BADLANDS, PLATEAU, SHATTERED, WINDSWEPT_SAVANNA, PEAKS} biomes;

void biomeEffects(biomes selectedBiome);